### ISSUE TITLE
mix test error (after install)

### ISSUE THREAD

**Issue by MarcusE1W** [wende/elchemy#187]
After installing elixir, elm, elm-github-install (this requirement could be better documented:-) and elchemy I tried to follow the article and eventually tried the `mix test` command for the first time.

After a while of running I got a compile error. 
[error log](https://gist.github.com/anonymous/16a8e17162749757b2bbd7e213e62a4f)

Am I missing any steps?

Not sure if this is related but this step: Getting updates for: wende/elchemy-core takes quite a lot of time. Also if I repeat `mix test` command it takes the same time. 

Any help appreciated.

**Comment by wende** [comment]
A regex for directories snook in with latest release. It changed `elm-stuff` to `lib-stuff` instead of `elm-deps` (You can see that in your output.)

Version 0.4.36

You should be able to retry with:
```bash
cd your_project
npm install -g elchemy
elchemy version # (Should print 0.4.36 or higher)
elchemy clean
elchemy init # (Then yes)
mix test
```
About the time of running it's suspicious, on my machine the entire process takes about 15 seconds for fresh project, and +/- 1 second for elchemy-core.
<img width="890" alt="screen shot 2017-09-05 at 17 31 13" src="https://user-images.githubusercontent.com/4634386/30069105-0b56a996-9260-11e7-8c57-14f65441eec7.png">

**Comment by wende** [comment]
@MarcusE1W 
I just installed latest version of elm-github-install and it takes a lot of time for me too.
Try installing previous version with:
```
npm install -g elm-github-install@1.2.0
```

**Comment by MarcusE1W** [comment]
Success :-)
4.36 solved the compile error. After that the test ran already successfuly.

Installing elm-github-install@1.2.0 has sped up the process nicely.
Thanks for the super quick help.

**Comment by wende** [comment]
@MarcusE1W 
Glad to help!
Would love to hear any feedback on elchemy if you feel like anything needs addressing! Enjoy 🎉
