### ISSUE TITLE
Allow forward reference of variables in let..in

### ISSUE THREAD

**Issue by wende** [wende/elchemy#198]
Example:

```
let
   a = b + 1
   b = 2
in
   a
```

**Comment by wende** [comment]
Great tool that might help:
https://github.com/vic/having/blob/master/test/having_test.exs#L39

**Comment by wende** [comment]
To be honest I'm a little bit out of ideas.

With the variables it's not so hard given that
```
a = b
b = a
```
Won't ever have any meaning. The problem is 
```
a x = b x
b x = a x
```
Does have a meaning and should be possible.
If it was JavaScript the implementation wouldn't be that hard with
```
var a,b;
a = (x) => b(x);
b = (x) => a(x);
```
But in elixir unfortunately it isn't so simple due to good practices of immutability

**Comment by wende** [comment]
And all of the solutions with combinators probably won't be as nice to look at

**Comment by OvermindDL1** [comment]
Personally I'd just fail in such a situation as it does not make sense on the beam.  You could use a y-combinator to make it work though, but honestly I'd just fail it.

**Comment by wende** [comment]
@OvermindDL1 But what about Elm libraries that use it?
This actually is the way it's been discovered. While compiling Elchemy with itself it turns out List.Extra uses it this way. But that's actually true that doing a graph and solving it by sorting the variables in correct order should fix 99% of the cases

**Comment by OvermindDL1** [comment]
Hmm, you might need to create the combinator inline then...  ^.^;

At least it is not hard, it just adds an extra indirection on the calls, slowing them down 'slightly'.  What you could do instead is lift them out to be `defp` functions as they could trivially access each other then, but instead of them being closures you'd have to pass in closed-over bindings into the calls (not at all hard, heck I do it in my better `for` replacement at https://github.com/OvermindDL1/ex_core/blob/master/lib/ex_core/comprehension.ex where you can see that I lift the internal functions to be module level and instead of making an implicit closure I make an explicit closure by passing in the variables that it uses explicitly).

**Comment by wende** [comment]
This is exactly what I thought about, a macro that would make them functions inside a module. But it feels like a terrible overkill to define a module whenever there is more than one variable defined in let..in

**Comment by OvermindDL1** [comment]
Well don't define a module, just hoist them to functions in the module that the existing function is already defined in.  :-)

Like both elixir's `for` and my `comp` hoist to a function of the same name as the function they are inside of along with extra data to make it unique (and with `$` to make it difficult for a person to accidentally name a function the same as the helper as well).  :-)

**Comment by wende** [comment]
Ooooh. That's sneaky. It could work. Just need to figure out a way for it to not sacrifice output readability

**Comment by OvermindDL1** [comment]
> Ooooh. That's sneaky. It could work. Just need to figure out a way for it to not sacrifice output readability

Lol, not as sneaky as you'd think, such hidden functions are generated with impunity by Elixir for all kinds of things like defoverride, for/with, defmodule, etc... etc...  ^.^

But I'd find it perfectly readable still if they were just named decently based on the parent function name.  :-)

**Comment by wende** [comment]
Right now the context stores all the local variables so with a little bit of effort it could be promoted to something like

```elm
module A exposing (test)
moreBy a by = 
  let
    addBy a = id a + by
    id x = x
  in 
   addBy a
```
Could be resolved to
```elixir
defmodule A do
  def more_by(a, by) do
    more_by__add_by(a, [a: a, by: by]) # Passes all local variables as a context
  end

  defp more_by__add_by(a, context), do: id(a) + context[by]
  defp more_by__id(a, context), do: a
end
```

Which seems like a most explicit way to do that, which unfortunately can become very tricky with further nestings of let..ins.

Second approach would be to do virtually the same but hiding all of it under macros. 

@OvermindDL1 How would your approach deal with shadowing?
Ex:
```elm
let 
  f a = a + 1
  b a = 
    let
      f a = a +2
    in 
      f(1)
in 
  f(2)
```

**Comment by OvermindDL1** [comment]
> @OvermindDL1 How would your approach deal with shadowing?

Well in my `comp` case, such a setup defines functions with their names in the format of:
https://github.com/OvermindDL1/ex_core/blob/master/lib/ex_core/comprehension.ex#L59

```elixir
name = "$comp_#{elem(env.function, 0)}_#{elem(env.function, 1)}_#{env.line}"
```

So if your code was like:

```elm
blah = (* line 1 *)
  let 
    f a = a + 1
    b a = 
      let
        f a = a +2
      in 
        f(1)
  in 
    f(2)
```

Then it would create code kind of like (I'm not adding a `$` in the name, but it might be good to prevent accidental usage, you'd need to sacrifice a touch of readability by `unquote(:"$blah_0_3")` and such for example though):

```elixir
def blah() do
  blah_0_3_f(2)
end

defp blah_0_3_f(a) do
  a + 1
end

defp blah_0_4_b(a) do
  blah_0_6_f(1)
end

defp blah_0_6_b_f(a) do
  a + 2
end
```

Although I'm not sure there is a point to generate the b or b_f functions since they are not used and they are internal only...?

**Comment by OvermindDL1** [comment]
Also, for note:

> more_by__add_by(a, [a: a, by: by]) # Passes all local variables as a context

These keyword list lookups would not be very fast, you really should unpack the used arguments only (ignoring unused ones, I.E. make a proper closure reducer, they are not hard at all) and unpack them as the first arguments to the functions, like my `comp` does (feel free to give `comp` a try, you can scatter some `Macro.to_string`'s around to see the code it generates (or I can if you have a specific example in mind?).  :-)
