### ISSUE TITLE
Allow passing of uncurried functions from outside of Elchemy and treat them as regular curried versions

### ISSUE THREAD

**Issue by timCF** [wende/elchemy#218]
## Example:
```elm
module Hello exposing (..)

reduce : List a -> b -> (a -> b -> b) -> b
reduce list acc func =
  case list of
    [] ->
      acc
    head::tail ->
      reduce tail (func head acc) func
```
->
```elixir
# Compiled using Elchemy v0.4.12
defmodule Hello do
  use Elchemy

  @spec reduce(list(any), any, (any -> (any -> any))) :: any
  curry reduce/3
  def reduce(list, acc, func) do
    case list do
      [] ->
        acc
      [head | tail] ->
        reduce().(tail).(func.(head).(acc)).(func)
    end
  end

end
```

Hello! The question is about this line
```elixir
reduce().(tail).(func.(head).(acc)).(func)
```
Any plans to improve it to "normal" Elixir-style code? 
Like this
```elixir
reduce(tail, func.(head, acc), func)
```
1) For better performance
2) For better compatibility with Elixir code (in case of calling Elchemy code from Elixir).

**Comment by timCF** [comment]
example of performance test
```elixir
lst = Enum.to_list(1..10_000_000)                                    
Hello.Elchemy.reduce(lst, 0, fn(x) -> &(&1 + x) end) # Finished in 45.9 seconds
Hello.Elixir.reduce(lst, 0, &(&2 + &1))                            # Finished in 40.2 seconds
```
Also ofc for Elixir developers much more expected are lambda-functions without currying. For example if I write library in Elchemy and share it for Elixir project

**Comment by wende** [comment]
Hi @timCF! Thanks for your interest
For currying on full function calls it was already done by #201 and it should be in version 4.30+
<img width="1351" alt="screen shot 2017-11-08 at 13 43 01" src="https://user-images.githubusercontent.com/4634386/32549751-e37722a4-c48a-11e7-842a-fff2b065dfb2.png">
The uncurried anonymous functions is a much harder topic. I don't think it is possible to a manageable extent to operate on more-than-one argument lambdas, since every variable would have to contain a meta information about its real arity and reflect that when applied. 
Obviously the type system provides information like that it is a complicated topic to grasp and the gains of having it would be minor. 
So the answer to that would be "not planned for near future"

**Comment by wende** [comment]
Regarding external use: right now when using the external libraries with `ffi` call it recognizes lambdas based on definition and changes N arity functions into curried version of it.
f.i
```elm
reduce : List a -> b -> (a -> b -> b) -> b
reduce list acc func =
  ffi "Enum" "reduce"
```
-->
```elixir
  @spec reduce(list(any), any, (any -> (any -> any))) :: any
  curry reduce/3
  verify as: Enum.reduce/3
  def reduce(a1, a2, a3), do: Enum.reduce(a1, a2, fn (x1,x2) -> a3.(x1).(x2) end)
```
So it definitely works one way.
There should be a way to allow the function to take bigger arity functions from outside. I agree.
Since there is a guard of `is_function/2` which takes an arity as a second argument, I believe it should be possible to give some tool (wort case scenario a compiler flag) to export functions with their uncurried function versions.

The simplest solution that comes to my mind would be to add to the compiler to recognize the function arguments and add it to `curry` macro so that a real expanded version would look like:
```elixir
def function(a,b,c, f) when is_function(f) and not is_function(f, 1) do
   function(a, b, c, make_curried(f))
end
def function(a, b, c, f) do 
  # real implementation
end
```

**Comment by wende** [comment]
To play with the latest development version of the parser you can now go to
https://wende.github.io/elchemy/stable/

**Comment by wende** [comment]
Changing the name of the issue to reflect the fixable issue which is the external function uncurrying. Omitting of internal currying for optimization is considered a wontfix for now.

**Comment by timCF** [comment]
Hi @wende! Thank you for this compiler :)

I'm programming on Elixir / Erlang since 2012 and always dreamed about static typing in BEAM. It's not first attempt, but it looks promising, now with Elchemy and Alpaca we have hope.

> There should be a way to allow the function to take bigger arity functions from outside

Regarding Elchemy I think it's very important to provide this for better compatibility with Elixir and less aggression from Elixir developers when they will meet auto-generated code in real Elixir projects :) Let's be honest, Elixir today is famous because of Phoenix / Ecto and some other mainstream frameworks. Of course OTP too. Because of some Elchemy limitations (no metaprogramming / macto etc) it seems very difficult to write big phoenix application using Elchemy only. But Elchemy is good opportunity to write pure business logic. It's good opportunity to write some small libraries, packages, maybe small specialized OTP applications. So straightforward, trivial calling of Elchemy functions from Elixir is key to success. 100% backward compatibility
 of Erlang functions and all OTP goodies in pretty new Elixir language made it successful. Of course when we deal with another type system - things becomes not trivial. Very simple example - `send` function what is base for messaging between Erlang processes. How can you proof its type in compile time? :) Providing of equivalent of Phoenix / Ecto / OTP goodies in Elchemy is very big and hard task, so I think today writing of small pieces of pure business logic is thing what I want Elchemy use for.

Sorry for long topic :)

**Comment by wende** [comment]
@timCF I'm glad to hear you're interested!
Yes. Definitely everything regarding macros is gonna be a hard thing to port to Elchemy.
I've got plans for how to do send and receive type safe (If a process has a type then so has its messages) but generally porting stuff like Phoenix and Ecto is gonna be a long way to go and a lot of wrappers to do before it's usable in any way.
So far we're not giving up and Elchemy didn't lose it's "looks promising" factor over last 8 months of development :D 
Feel free to contribute and/or share your ideas. We're always open for discussion

**Comment by wende** [comment]
@timCF 
Curry macro in #235  now has a second parameter so that it gets generated as:
```elixir
curry function/2, lambdas: [{Int, Int}]
```
where a list in lambdas consists of tuples {index, arity}, when it has functions bigger than 1.
The macro then does another function clause for each element in a list. For instance
```elixir
curry function/3, lambdas: [{0, 2}, {2, 3}]
def function(a, b, c)
```
becomes
```elixir
def function() do # .... curried version ...
def function(a, b, c) when is_function(a, 2) and is_function(c, 3) do
  a = fn x1 -> fn x2 -> a.(x1, x2) end end
  c = fn x1 -> fn x2 -> x3 -> c.(x1, x2, x2) end end end
  function(a, b, c)
end
def function(a, b, c) # Regular definition
```
