### ISSUE TITLE
Is there a roadmap? 

### ISSUE THREAD

**Issue by puruzio** [wende/elchemy#240]
I am really excited to learn about this project. Are there any things that Elchemy won't be able to do that Elixir can? In other words, can Elchemy completely replace Elixir? If not, why? 

Where on your development roadmap are you today and what more do you expect to get done in the future? 

Thanks.

**Comment by wende** [comment]
We're using ZenHub to manage tasks and their priorities (no affiliation but couldn't recommend it more)
There is a plan for a stable version without effects (Cmd/Sub/Task) involved on one year anniversary of the project which is 20th February 2018.
You can see current burndown here
<img width="1030" alt="screen shot 2017-12-17 at 20 15 08" src="https://user-images.githubusercontent.com/4634386/34082901-439fc7da-e367-11e7-90c3-92d92cb4e100.png">
 
So far I can't see any limitations for Elchemy as a language for the Beam, but these obviously will start to show when we introduce the effects. The biggest concerns right now are of an architectural nature - how to rewrite OTP? How to make a type-safe GenServer that still will be familiar to Erlang/Elixir developers, but not sacrificing any of the type safety or lessons learned from The Elm Architecture.

But it's all about making possible sacrifices to the patterns we know, rather than limiting the functionality.
The only limitation I can think of right now (regarding Effects) is that there won't be `send` and `receive` as we know of in Erlang because they're causing an effect of blocking. Instead, Elchemy will be embracing building everything as a GenServer, which is a correct way to do it in every day Elixir development anyway. 

Will it ever be possible to write 100% Elchemy projects without any Erlang/Elixir code? I can't tell, probably not soon, but I think it should be possible to write the main functionality in Elchemy and writing bridge-code to libraries and low-level calls using Elixir for sure.

Until then, feel free to experiment, discuss and share cool project ideas under
https://gitter.im/elchemy-lang/
