### ISSUE TITLE
- No runtime errors claim in README is too strong

### ISSUE THREAD

**Issue by Qqwy** [wende/elchemy#241]
The readme currently states that having runtime errors is impossible.

Now, unless Elmchemy's type system is rigorously stronger than both Elm's and Haskell's, this is unfortunately not true.

Are things like potential division by zero prevented at compile time? If not, then there are still errors, and it would be good to clarify this in the readme.

**Comment by wende** [comment]
The runtime-error safety is as strong as Elm's (plus additional safety layer for the interop)
But I agree, given the "no runtime errors" is more of a path rather than a destination

**Comment by OvermindDL1** [comment]
> The runtime-error safety is as strong as Elm's (plus additional safety layer for the interop)
But I agree, given the "no runtime errors" is more of a path rather than a destination

Elm's is actually not very strong, like at all.  You can find a *lot* of runtime errors in their issue tracker because of language design decisions (like their fake `number` and so forth fake typeclases, NaN's and such filtering in to the integers transparently, many many others).

**Comment by wende** [comment]
@OvermindDL1 Yeah, this project made me find a lot of less than perfect solutions already.
Do you have any suggestions on which we could improve (based on Elm experience) to avoid the same mistakes?

**Comment by OvermindDL1** [comment]
> Do you have any suggestions on which we could improve (based on Elm experience) to avoid the same mistakes?

It's type system is not really strong enough to fix of the issues.  The rest of the issues were just bad javascript generation (Elm generates pretty horrible javascript code, especially compared to, say, [bucklescript](https://bucklescript.github.io/bucklescript-playground/) for example.

_/me as an aside, would have picked OCaml as the language to transpile to Elixir instead of Elm, similar syntax, significantly more powerful type system, much faster to compile, among a few dozen other reasons over Elm..._
