### ISSUE TITLE
Does the interop include dynamic types?

### ISSUE THREAD

**Issue by ShalokShalom** [wende/elchemy#255]
Does the Elixir interop include dynamic types?

**Comment by wende** [comment]
Could you elaborate on what do you mean by `include` and `dynamic` in this context?

**Comment by ShalokShalom** [comment]
Well, can I do dynamic typing in your language due to the interop?

**Comment by Hajto** [comment]
Whole purpose of this project is to have static typing. If you're asking if there is type inference then @wende  has to answer.

**Comment by ShalokShalom** [comment]
No, not type inference. I simply ask, if I can use dynamic types from within the interop mode
Since all that code here compiles into the BEAM, that should be possible, yeah?

**Comment by ShalokShalom** [comment]
Since [this homepage](http://blog.neontree.pl/) seems to be closed source, I drop this off-topic here: 
Your blog is down

**Comment by wende** [comment]
@ShalokShalom I'm having difficulties understanding your query so I'll try to spray and pray with my answer.
There are two types of interop in Elchemy:

The clean and nice one - [Elchemy.ffi/2](https://github.com/wende/elchemy-core/blob/master/DOCS.md#ffi) - which does the type checking. It's not 100% accurate (it's a as accurate as the `@spec` written for the file, so basically as accurate as Dialyzer would be). So no, it's not suitable for 'dynamic' typing.

The ugly and last-resort one, which is Elixir code injection with `{- ex  ... -}` which I'm assuming you meant by saying 'interop mode'. Basically it's unchecked and is exactly same as if you were writing Elixir in .ex file, the only purpose of it is to express some additional code that couldn't be expressed otherwise, like for example when writing a wrapper for a complex library that uses a lot of macro and `use Module`; or when you really need an Elixir function to help with your `ffi` interop, but don't want to create an entire module just for one function. Like we did here:
https://github.com/wende/elchemy-core/blob/master/elm/Elchemy/XBasics.elm#L89-L107

There is no other way of interacting with elixir than two above.

And yes, all the code compiles into the BEAM.
Does that answer your question?

> Since this homepage seems to be closed source, I drop this off-topic here:
Your blog is down
Thank you. Didn't notice that

**Comment by ShalokShalom** [comment]
> The ugly and last-resort one, which is Elixir code injection with {- ex ... -} which I'm assuming you meant by saying 'interop mode'. Basically it's unchecked and is exactly same as if you were writing Elixir in .ex file, the only purpose of it is to express some additional code that couldn't be expressed otherwise, like for example when 

.. I like dynamic types, yes? ;) 

Sometimes it makes sense to do so, even when I prefer static type with inference checking same as you.

**Comment by wende** [comment]
@ShalokShalom 
About documenting that there is a project as a guide to Elchemy that mentions it:
https://wende.github.io/elchemy-ivy/
But I'm slowly leaning towards just writing an MD roadmap folder in this repo In which I'd write all of the future plans and also completed features of Elchemy

**Comment by ShalokShalom** [comment]
Sounds nice
