### ISSUE TITLE
Umbrella apps support

### ISSUE THREAD

**Issue by nurges** [wende/elchemy#321]
Elchemy gives an error when executing 'mix compile' in an umbrella app.

It is caused by a format command in elchemy/lib/mix/tasks/compile.elchemy.ex

`Mix.Task.run("format", ["lib/**/*.elchemy.{ex,exs}"])`

A workaround is to create a 'lib' folder in umbrella app root and copy 'Hello.elchemy.ex' into this folder.

**Comment by wende** [comment]
@nurges Great find! 
I think given that we just want to format all of the elchemy files it could be changed to just `"./**/*.elchemy.{ex,exs}"` assuming such a wildcard works correctly

**Comment by wende** [comment]
After investigating an issue it seems that to make it work for umbrella apps it'd require a lot of changes to the main bash file, which is undergoing a big overhaul anyway due to #288.

Elchemy can still be used in every single app **inside** of the umbrella app. That means that the code between the apps can be used on an elixir interop (with `ffi` or using Elixir injection) but not on an Elchemy interop (It won't see the types out of the app)

Putting this to the backlog after dependency gets of #288 gets fixed
